<?php

namespace Database\Seeders;

use App\Models\Matkul as ModelsMatkul;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class MatkulSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $matkul = [
            ['id'          => '1604C011',
             'nama_matkul' => 'Algoritm & Programming'
            ],
            ['id'          => '1604Z013',
             'nama_matkul' => 'Literasi Digital'
            ],
            ['id'          => '1604Z012',
             'nama_matkul' => 'Manusia & Pengembangan Diri',
            ],
            ['id'          => '1604C012',
             'nama_matkul' => 'Introduction To Computer Science',
            ],
            ['id'          => '1604Z002',
             'nama_matkul' => 'Pancasila & Kewarganegaraan',
            ],
            ['id'          => '1604C021',
             'nama_matkul' => 'Object Oriented Programming',
            ],
            ['id'          => '1604C024',
             'nama_matkul' => 'Human Computer Interaction',
            ],
            ['id'          => '1604Z014',
             'nama_matkul' => 'Communicative English',
            ],
            ['id'          => '1000C003',
             'nama_matkul' => 'Pendidikan Agama Kristen',
            ],
            ['id'          => '1000C004',
             'nama_matkul' => 'Pendidikan Agama Katolik',
            ],
            ['id'          => '1000C051',
             'nama_matkul' => 'Pendidikan Agama Islam',
            ],
            ['id'          => '1000C006',
             'nama_matkul' => 'Pendidikan Agama Hindu',
            ],
            ['id'          => '1000C007',
             'nama_matkul' => 'Pendidikan Agama Buddha',
            ],
            ['id'          => '1000C008',
             'nama_matkul' => 'Pendidikan Agama Khonghucu',
            ],
            ['id'          => '1604C022',
             'nama_matkul' => 'Operating System',
            ],
            ['id'          => '1604C023',
             'nama_matkul' => 'Statistics',
            ],
            ['id'          => '1600C104',
             'nama_matkul' => 'Mathematics',
            ],
            ['id'          => '1604C031',
             'nama_matkul' => 'Data Structure',
            ],
            ['id'          => '1604C033',
             'nama_matkul' => 'Database',
            ],
            ['id'          => '1604C032',
             'nama_matkul' => 'Computer Network',
            ],
            ['id'          => '1604C331',
             'nama_matkul' => 'Physical Based Animation',
            ],
            ['id'          => '1604C331',
             'nama_matkul' => 'Data Mining',
            ],
            ['id'          => '1600C001',
             'nama_matkul' => 'Komposisi Bahasa Indonesia',
            ],
            ['id'          => '1604C034',
             'nama_matkul' => 'Software Engineering',
            ],
            ['id'          => '1608C051',
             'nama_matkul' => 'Game Concept & Design',
            ],
            ['id'          => '1604C131',
             'nama_matkul' => 'Management Information System',
            ],
            ['id'          => '1604C045',
             'nama_matkul' => 'Information Security and Assurance',
            ],
            ['id'          => '1604C431',
             'nama_matkul' => 'Internet of Things',
            ],
            ['id'          => '1608C031',
             'nama_matkul' => 'Basic Multimedia Design',
            ],
            ['id'          => '1608C032',
             'nama_matkul' => 'Basic Multimedia Drawing',
            ],
            ['id'          => '1600C106',
             'nama_matkul' => 'Aljabar Linear',
            ],
            ['id'          => '1604C042',
             'nama_matkul' => 'Ai Fundamental',
            ],
            ['id'          => '1604C043',
             'nama_matkul' => 'Web Programming',
            ],
            ['id'          => '1604C044',
             'nama_matkul' => 'Distributed Programming',
            ],
            ['id'          => '1604C046',
             'nama_matkul' => 'Data Science Programming',
            ],
            ['id'          => '1604C341',
             'nama_matkul' => 'Applied Multivarite Analysis',
            ],
            ['id'          => '1604C241',
             'nama_matkul' => 'Game Modelling & Animation',
            ],
            ['id'          => '1604C141',
             'nama_matkul' => 'Applied Database',
            ],
            ['id'          => '1608C043',
             'nama_matkul' => 'Multimedia Composition & Layout',
            ],
            ['id'          => '1604C051',
             'nama_matkul' => 'Full-Stack Programming',
            ],
            ['id'          => '1604C052',
             'nama_matkul' => 'Native Mobile Programming',
            ],
            ['id'          => '1604C053',
             'nama_matkul' => 'Numerical Methods',
            ],
            ['id'          => '1604C054',
             'nama_matkul' => 'Hybrid Mobile Programming',
            ],
            ['id'          => '1604C055',
             'nama_matkul' => 'Machine Learning',
            ],
            ['id'          => '1604C362',
             'nama_matkul' => 'Intelligent Information System Retrieval',
            ],
            ['id'          => '1604C251',
             'nama_matkul' => 'Game Programming',
            ],
            ['id'          => '1604C151',
             'nama_matkul' => 'Database Management',
            ],
            ['id'          => '1608C451',
             'nama_matkul' => 'Cryptography',
            ],
            ['id'          => '1608C052',
             'nama_matkul' => 'Digital Video',
            ],
            ['id'          => '1608C053',
             'nama_matkul' => '3D Animation',
            ],
            ['id'          => '1604Z001',
             'nama_matkul' => 'Kewirausahaan & Inovasi',
            ],
            ['id'          => '1604C061',
             'nama_matkul' => 'Leadeship & Professional Ethics',
            ],
            ['id'          => '1604C062',
             'nama_matkul' => 'Advanced Native Mobile Programming',
            ],
            ['id'          => '1604C063',
             'nama_matkul' => 'Web Framework Programming',
            ],
            ['id'          => '1604C361',
             'nama_matkul' => 'Operation Research',
            ],
            ['id'          => '1604C351',
             'nama_matkul' => 'Digital Image Processing',
            ],
            ['id'          => '1604C261',
             'nama_matkul' => 'Mixed Reality',
            ],
            ['id'          => '1604C262',
             'nama_matkul' => 'Mobile Game Programming',
            ],
            ['id'          => '1604C161',
             'nama_matkul' => 'Supply Chain Management Accounting System',
            ],
            ['id'          => '1604C162',
             'nama_matkul' => 'Enterprise System Implementation',
            ],
            ['id'          => '1604C461',
             'nama_matkul' => 'Digital Forensics',
            ],
            ['id'          => '1604C462',
             'nama_matkul' => 'Network Security Implementation',
            ],
            ['id'          => '1608C061',
             'nama_matkul' => 'Game Engineering',
            ],
            ['id'          => '1608C062',
             'nama_matkul' => 'Digital Video Editing',
            ],
            ['id'          => '1604C071',
             'nama_matkul' => 'Research Methodology',
            ],
            ['id'          => '1604C081',
             'nama_matkul' => 'Tugas Akhir',
            ],
        ];
        foreach($matkul as $i){
            ModelsMatkul::create($i);
        }
    }
}
